name: Send Webhook Message
on:
  push:
    branches: ["main"]
    paths:
      - "bot/**"
      - "dbm/**"
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Message
        uses: tsickert/discord-webhook@v7.0.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
          embed-title: "[DBM-v14] new commit"
          embed-description: "${{ github.event.head_commit.message }}"
          embed-url: "${{ github.event.head_commit.url }}"
          embed-color: 65297
          embed-timestamp: "${{ github.event.head_commit.timestamp }}"
          embed-thumbnail-url: "https://github.com/shadoow051/DBM-v14/raw/main/docs/img/dbm-poland.png"
          embed-author-name: "${{ github.actor }}"
          embed-author-url: "https://github.com/${{ github.actor }}"
          embed-author-icon-url: "https://avatars.githubusercontent.com/${{ github.actor }}"
