name: Send Webhook Message
on:
  push:
    branches: ["main"]
    paths:
      - "bot/**"
      - "dbm/**"
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Message
        uses: Ilshidur/action-discord@ad5235de713df3ef38022185499b02ffe93b7efe
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: |
            {
              "embeds": [
                {
                  "title": "[DBM-v14] new commit",
                  "description": "${{ github.event.head_commit.message }}",
                  "url": "${{ github.event.head_commit.url }}"
                  "color": 65297,
                  "timestamp": "${{ github.event.head_commit.timestamp }}",
                  "thumbnail": {
                    "url": "https://github.com/shadoow051/DBM-v14/blob/main/docs/img/dbm-poland.png?raw=true"
                  },
                  "author": {
                    "name": "${{ github.actor }}",
                    "url": "https://github.com/${{ github.actor }}",
                    "icon_url": "https://avatars.githubusercontent.com/${{ github.actor }}"
                  }
                }
              ]
            }
