name: Update Version Branch

on:
  push:
    branches: ["main"]
    paths:
      - "bot/**"
      - "dbm/**"

permissions:
  contents: write

jobs:
  update_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get DBM version
        run: |
          FULL_VERSION=$(jq -r '.version' bot/package.json)
          BRANCH_NAME="v$(echo $FULL_VERSION | awk -F. '{print $1"."$2}')"
          echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create or switch to version branch
        run: |
          if git show-ref --verify --quiet refs/heads/$BRANCH_NAME; then
            git checkout $BRANCH_NAME
          else
            git checkout --orphan $BRANCH_NAME
            git rm -rf . || true
          fi

      - name: Copy only dbm, bot, LICENSE and README.md
        run: |
          git checkout main -- dbm bot LICENSE README.md || true

      - name: Commit and push
        run: |
          git add dbm bot LICENSE README.md
          git commit -m "Update branch $BRANCH_NAME" || echo "No changes to commit"
          git push origin $BRANCH_NAME --force
